/**
 * Derive the coloured logo variants in `src/assets/logo/` from the one master path.
 *
 * Run by hand after `mark.svg` changes: `tsx scripts/generateLogoVariants.ts`. Not part of the
 * build - the artwork changes about as often as the name does, and the variants are committed so
 * they can be referenced like any other asset.
 *
 * **Why a script rather than twelve hand-kept files.** The traced path is 27KB and identical in
 * every one of them; only three attributes differ. Editing the artwork would otherwise mean
 * editing it twelve times, and the twelfth would be the one that drifts.
 *
 * ## The three treatments
 *
 * **`mark-<hue>`** is the bare silhouette, no disc, filled with the hue. It is the one that
 * survives an unknown background - it has no disc to be lost against a light or dark chrome -
 * and the one to reach for wherever something else already supplies the surface.
 *
 * **`disc-<hue>`** is the badge: the mark in white on a filled disc, the treatment for anywhere
 * the icon has to hold its own shape against a background nobody chose (a browser tab, a home
 * screen, a launcher).
 *
 * **`disc-<hue>-inverted`** swaps them, and comes with a caveat worth writing down: the white
 * disc disappears against a white ground, so the badge silently becomes the bare mark. It reads
 * best on a mid-tone or dark surface, which means it is a lockup for places where the background
 * is known, never a favicon.
 *
 * ## Two numbers
 *
 * The disc variants inset the mark to 38 of the 48 units, and re-add the 100-unit stroke the
 * master drops (see `mark.svg`), in the *disc* colour. Both are for small sizes: the inset keeps
 * the mark off the disc's edge, and the stroke widens the holes in the path so the shapes still
 * separate at 16px instead of closing into a blob. The bare variants take neither - at 46 units
 * they fill the box, and with no disc behind them there is no background colour to stroke with.
 */
import { readFileSync, writeFileSync } from "node:fs";

/** The mark's own bounding box within the 1254-unit master viewBox; it is not centred in it. */
const BOUNDS = { x: 69.874, y: 93.738, width: 1106.133, height: 1072.059 };

const HUES: Record<string, string> = {
  teal: "#2a9d97",
  "deep-teal": "#17827d",
  "river-blue": "#1f6fa8",
  plum: "#6b4fc0",
};

const WHITE = "#ffffff";
const MASTER = "src/assets/logo/mark.svg";
const pathData = readFileSync(MASTER, "utf8").match(/<path[^>]*\sd="([^"]*)"/)?.[1];
if (!pathData) throw new Error(`no path found in ${MASTER}`);

/** Fit the mark to `span` of the 48-unit icon box, centred on its own bounds rather than the viewBox. */
function placeMark(span: number, fill: string, stroke: string | null): string {
  const scale = span / Math.max(BOUNDS.width, BOUNDS.height);
  const translateX = 24 - (BOUNDS.x + BOUNDS.width / 2) * scale;
  const translateY = 24 - (BOUNDS.y + BOUNDS.height / 2) * scale;
  const strokeAttrs = stroke
    ? ` stroke="${stroke}" stroke-width="100" stroke-linejoin="round" stroke-linecap="round" paint-order="stroke"`
    : "";
  return [
    `  <g transform="translate(${translateX.toFixed(3)} ${translateY.toFixed(3)}) scale(${scale.toFixed(6)})">`,
    `    <path d="${pathData}" fill="${fill}" fill-rule="evenodd"${strokeAttrs}/>`,
    `  </g>`,
  ].join("\n");
}

function variant(note: string, disc: string | null, fill: string, span: number): string {
  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!-- ${note}`,
    `     Generated by scripts/generateLogoVariants.ts from src/assets/logo/mark.svg. Do not edit:`,
    `     change the master or the script and rerun \`tsx scripts/generateLogoVariants.ts\`. -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">`,
    ...(disc ? [`  <circle cx="24" cy="24" r="24" fill="${disc}"/>`] : []),
    placeMark(span, fill, disc),
    `</svg>`,
    ``,
  ].join("\n");
}

const written = Object.entries(HUES).flatMap(([name, hue]) => [
  [`src/assets/logo/mark-${name}.svg`, variant(`Corrente's mark in ${name} (${hue}), no disc.`, null, hue, 46)],
  [`src/assets/logo/disc-${name}.svg`, variant(`Corrente's mark in white on a ${name} (${hue}) disc.`, hue, WHITE, 38)],
  [
    `src/assets/logo/disc-${name}-inverted.svg`,
    variant(`Corrente's mark in ${name} (${hue}) on a white disc. Needs a mid-tone or dark ground.`, WHITE, hue, 38),
  ],
]);

for (const [file, contents] of written) {
  writeFileSync(file, contents);
  console.log(file);
}
