/**
 * Derive the coloured logo variants in `src/assets/logo/` from the one master path.
 *
 * Run by hand after `mark.svg` changes: `tsx scripts/generateLogoVariants.ts`. Not part of the
 * build - the artwork changes about as often as the name does, and the variants are committed so
 * they can be referenced like any other asset.
 *
 * **Why a script rather than twelve hand-kept files.** The traced path is 27KB and identical in
 * every one of them; only three attributes differ. Editing the artwork would otherwise mean
 * editing it twelve times, and the twelfth would be the one that drifts.
 *
 * ## The three treatments
 *
 * **`disc-<hue>`** is the badge: the mark in white on a filled disc. One confident shape, which is
 * what a surface nobody chose needs - a launcher, a home screen, a light frame.
 *
 * **`disc-<hue>-outline`** fills the disc with the hue and paints the mark that same hue, so its
 * fill vanishes into the ground and only the white stroke is left: line art rather than a
 * silhouette. It wants a dark surround and around 32px before it earns its keep. The one thing the
 * baked file cannot carry is the hairline edge the in-app version wears, because that is mixed from
 * `--color-ink` and so belongs to a live theme.
 *
 * **`mark-<hue>-outlined`** is the bare silhouette with the white sticker outline the trace
 * originally shipped with. On white it is indistinguishable from the plain mark, since the halo
 * falls outside the shape; on anything darker it draws a sticker edge and opens the interior
 * separations. The favicon's treatment, because at 16px line art closes into a smudge.
 *
 * ## Two numbers
 *
 * Each treatment insets the mark by however much its own stroke and surround need, and the number
 * is not arbitrary in any of them. The 100-unit stroke re-adds what `mark.svg` drops, and it is
 * what keeps the holes in the path (the gunwale line, the guitar's outline) open at 16px instead
 * of closing into a blob.
 *
 * - `disc`: 38 of 48, stroked in the disc's own colour. The inset is what keeps the mark off the
 *   disc's edge.
 * - `disc-outline`: 34, the mark in the disc's own colour, stroked white.
 * - `mark-outlined`: 43, stroked white. A 100-unit stroke reaches 50 units past the path on each
 *   side, which at this scale is about 2 units of the 48 - so 43 is the largest the mark can be
 *   drawn before its own halo is clipped by the viewBox.
 */
import { readFileSync, writeFileSync } from "node:fs";

/** The mark's own bounding box within the 1254-unit master viewBox; it is not centred in it. */
const BOUNDS = { x: 69.874, y: 93.738, width: 1106.133, height: 1072.059 };

const HUES: Record<string, string> = { plum: "#6b4fc0" };

const WHITE = "#ffffff";
const MASTER = "src/assets/logo/mark.svg";
const pathData = readFileSync(MASTER, "utf8").match(/<path[^>]*\sd="([^"]*)"/)?.[1];
if (!pathData) throw new Error(`no path found in ${MASTER}`);

/** Fit the mark to `span` of the 48-unit icon box, centred on its own bounds rather than the viewBox. */
function placeMark(span: number, fill: string, stroke: string | null): string {
  const scale = span / Math.max(BOUNDS.width, BOUNDS.height);
  const translateX = 24 - (BOUNDS.x + BOUNDS.width / 2) * scale;
  const translateY = 24 - (BOUNDS.y + BOUNDS.height / 2) * scale;
  const strokeAttrs = stroke
    ? ` stroke="${stroke}" stroke-width="100" stroke-linejoin="round" stroke-linecap="round" paint-order="stroke"`
    : "";
  return [
    `  <g transform="translate(${translateX.toFixed(3)} ${translateY.toFixed(3)}) scale(${scale.toFixed(6)})">`,
    `    <path d="${pathData}" fill="${fill}" fill-rule="evenodd"${strokeAttrs}/>`,
    `  </g>`,
  ].join("\n");
}

function variant(note: string, disc: string | null, fill: string, span: number, stroke = disc): string {
  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!-- ${note}`,
    `     Generated by scripts/generateLogoVariants.ts from src/assets/logo/mark.svg. Do not edit:`,
    `     change the master or the script and rerun \`tsx scripts/generateLogoVariants.ts\`. -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">`,
    ...(disc ? [`  <circle cx="24" cy="24" r="24" fill="${disc}"/>`] : []),
    placeMark(span, fill, stroke),
    `</svg>`,
    ``,
  ].join("\n");
}

const written = Object.entries(HUES).flatMap(([name, hue]) => [
  [`src/assets/logo/disc-${name}.svg`, variant(`Corrente's mark in white on a ${name} (${hue}) disc.`, hue, WHITE, 38)],
  [
    `src/assets/logo/disc-${name}-outline.svg`,
    variant(`Corrente's mark as white line art on a ${name} (${hue}) disc.`, hue, hue, 34, WHITE),
  ],
  [
    `src/assets/logo/mark-${name}-outlined.svg`,
    variant(`Corrente's mark in ${name} (${hue}), no disc, with the white sticker outline.`, null, hue, 43, WHITE),
  ],
]);

for (const [file, contents] of written) {
  writeFileSync(file, contents);
  console.log(file);
}
